### ISSUE TITLE
OT 및 정기참석 시간과 장소

### ISSUE THREAD

**Issue by TEDD325** [modulabs/MODULABS-ai-contentcreators#3]
안녕하세요.
OT 당일 참석 시간 및 정기적 주 1회 참석의 정확한 시간을 알고 싶습니다. 시간에 따라 지원여부가 달라질 것 같습니다.
장소는 양재R&D 센터인 것 같은데 다시 한 번 확인 부탁드립니다.

감사합니다.

**Comment by uhmppi1** [comment]
현재로서는 1/14 (화) 오후 8시에 양재R&D센터에서 진행할 계획입니다.
변경이 있다면 사전에 다시 고지하도록 하겠습니다.

최종선발 이후 정기적 주 1회 참석 일정은 컨텐츠 제작자분의 개인적 스케줄을 반영하여 개별로 정할 예정입니다.
